### ISSUE TITLE
Attachment support

### ISSUE THREAD

**Issue by kirpit** [StackStorm-Exchange/stackstorm-email#10]
Hi there,

If I am not mistaken, there is no support for adding attachments to your emails at ATM. I can see some `attachments` parameter being parsed[1] but in sensors, not in actions.

I don't reckon it's too difficult to add this feature with backwards support. Wondering if is there anything that I need to pay attention (e.g.: tests) before start working on a PR for this issue?

[1]: https://github.com/StackStorm-Exchange/stackstorm-email/blob/master/sensors/smtp_sensor.yaml

**Comment by LindsayHill** [comment]
Should be straightforward. 

This pack sadly doesn't have any tests right now, but tests would of course be most welcome. See https://docs.stackstorm.com/development/pack_testing.html for more information about pack tests.

Make sure your code passes linting checks before submitting PR https://github.com/StackStorm/lint-configs

Those checks are done automatically on PR submission, but it's just that it's usually faster to fix those pesky line-length issues locally, rather than waiting for CircleCI to run.
